export const weatherIconsIndex = {
  "01d": "wi wi-day-sunny",
  "01n": "wi wi-night-clear",
  "02d": "wi wi-day-cloudy",
  "02n": "wi wi-night-alt-cloudy",
  "03d": "wi wi-cloudy",
  "03n": "wi wi-cloudy",
  "04d": "wi wi-cloudy",
  "04n": "wi wi-cloudy",
  "09d": "wi wi-rain",
  "09n": "wi wi-rain",
  "10d": "wi wi-day-rain",
  "10n": "wi wi-night-alt-rain",
  "11d": "wi wi-day-thunderstorm",
  "11n": "wi wi-night-alt-thunderstorm",
  "13d": "wi wi-day-snow",
  "13n": "wi wi-night-alt-snow",
  "50d": "wi wi-day-fog",
  "50n": "wi wi-night-fog",
};
